-- MySQL Script generated by MySQL Workbench
-- Tue May 24 11:54:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinemadatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinemadatabase` ;

-- -----------------------------------------------------
-- Schema cinemadatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinemadatabase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cinemadatabase` ;

-- -----------------------------------------------------
-- Table `cinemadatabase`.`information clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemadatabase`.`information clients` (
  `idclients` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idclients`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemadatabase`.`information films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemadatabase`.`information films` (
  `idinformation films` VARCHAR(5) NOT NULL,
  `titre` VARCHAR(60) NOT NULL,
  `date de sortie` DATE NOT NULL,
  `duree` VARCHAR(45) NOT NULL,
  `realisateur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinformation films`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemadatabase`.`categorie film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemadatabase`.`categorie film` (
  `idcategorie` INT NOT NULL,
  `action` VARCHAR(60) NOT NULL,
  `comedie` VARCHAR(60) NOT NULL,
  `aventure` VARCHAR(60) NOT NULL,
  `drame` VARCHAR(60) NOT NULL,
  `horreur` VARCHAR(60) NOT NULL,
  `information clients_idclients` INT NOT NULL,
  `information films_idinformation films` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idcategorie`, `information clients_idclients`),
  INDEX `fk_categorie film_information clients_idx` (`information clients_idclients` ASC) VISIBLE,
  INDEX `fk_categorie film_information films1_idx` (`information films_idinformation films` ASC) VISIBLE,
  CONSTRAINT `fk_categorie film_information clients`
    FOREIGN KEY (`information clients_idclients`)
    REFERENCES `cinemadatabase`.`information clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorie film_information films1`
    FOREIGN KEY (`information films_idinformation films`)
    REFERENCES `cinemadatabase`.`information films` (`idinformation films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemadatabase`.`mise a jour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemadatabase`.`mise a jour` (
  `idmiseajour` INT NOT NULL,
  `date de creation` DATE NOT NULL,
  `date modification` DATE NOT NULL,
  PRIMARY KEY (`idmiseajour`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemadatabase`.`film louee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemadatabase`.`film louee` (
  `idfilm` VARCHAR(5) NOT NULL,
  `date de location` DATE NOT NULL,
  `date de retour` DATE NOT NULL,
  `information clients_idclients` INT NOT NULL,
  `mise a jour_idmiseajour` INT NOT NULL,
  PRIMARY KEY (`idfilm`, `information clients_idclients`, `mise a jour_idmiseajour`),
  INDEX `fk_film louee_information clients1_idx` (`information clients_idclients` ASC) VISIBLE,
  INDEX `fk_film louee_mise a jour1_idx` (`mise a jour_idmiseajour` ASC) VISIBLE,
  CONSTRAINT `fk_film louee_information clients1`
    FOREIGN KEY (`information clients_idclients`)
    REFERENCES `cinemadatabase`.`information clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film louee_mise a jour1`
    FOREIGN KEY (`mise a jour_idmiseajour`)
    REFERENCES `cinemadatabase`.`mise a jour` (`idmiseajour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemadatabase`.`payement clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemadatabase`.`payement clients` (
  `idpayement` INT NOT NULL,
  `date de payement` DATE NOT NULL,
  `description` VARCHAR(60) NOT NULL,
  `montant` VARCHAR(45) NOT NULL,
  `information clients_idclients` INT NOT NULL,
  PRIMARY KEY (`idpayement`, `information clients_idclients`),
  INDEX `fk_payement clients_information clients1_idx` (`information clients_idclients` ASC) VISIBLE,
  CONSTRAINT `fk_payement clients_information clients1`
    FOREIGN KEY (`information clients_idclients`)
    REFERENCES `cinemadatabase`.`information clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
